baseURL = 'https://orbis-dei.github.io/'
languageCode = 'en-us'
title = 'Orbis Dei'
theme = 'PaperMod'

[menu]
[[menu.main]]
  name = 'Marian Sites'
  pageRef = 'tags/marian-sites'
  weight = 1
[[menu.main]]
  name = 'Saints and Holy Persons'
  pageRef = 'tags/holy-persons'
  weight = 2
[[menu.main]]
  name = 'Contact'
  pageRef = 'contact'
  weight = 3
