baseURL = 'https://orbisdei.org'
languageCode = 'en-us'
title = 'Orbis Dei'
theme = 'PaperMod'

[menu]
[[menu.main]]
  name = 'Marian Sites'
  pageRef = 'tags/marian-sites'
  weight = 1
[[menu.main]]
  name = 'Saints & Holy Persons'
  pageRef = 'tags/holy-persons'
  weight = 2
[[menu.main]]
  name = 'Search'
  pageRef = 'search'
  weight = 3
[[menu.main]]
  name = 'Contact'
  pageRef = 'contact'
  weight = 4
