baseURL = 'https://orbisdei.org'
languageCode = 'en-us'
title = 'Orbis Dei'
theme = 'PaperMod'

[menu]
[[menu.main]]
  name = 'Saints & Holy Persons'
  pageRef = 'tags/holy-persons'
  weight = 1
[[menu.main]]
  name = 'Marian Sites'
  pageRef = 'tags/marian-sites'
  weight = 2
[[menu.main]]
  name = 'About'
  pageRef = 'about'
  weight = 4
[[menu.main]]
  name = 'Contact'
  pageRef = 'contact'
  weight = 5

[services]
[services.googleAnalytics]
ID = 'G-XR25W3EJPR'
